language: java
jdk:
  - oraclejdk8
env:
  - PLAY_VERSION=1.3.10
before_script:
  - wget https://downloads.typesafe.com/typesafe-activator/${PLAY_VERSION}/typesafe-activator-${PLAY_VERSION}-minimal.zip
  - unzip -q typesafe-activator-${PLAY_VERSION}-minimal.zip
script: typesafe-activator-${PLAY_VERSION}-minimal/bin/activator test
